# If not running interactively, don't do anything
[[ $- != *i* ]] && return

uname="$(uname)"

# Set up make flags

if [ "$uname" = "FreeBSD" ]; then
    ncpus="$(sysctl -a | egrep -i 'hw.ncpu')"
else
    ncpus="$(nproc)"
fi

makejobs=""

# Special case for my desktop
if [ "$ncpus" == "12" ]; then 
    makejobs="10"
else
    makejobs="$ncpus"
fi

export MAKEFLAGS="-j$makejobs"

# End setting up make flags

# Set up useful aliases
if [ "$uname" = "FreeBSD" ]; then
    alias ls="ls -G"
    alias rm="rm -vxI" # verbose, one filesystem, confirm large removals
else
    alias ls="ls --color=auto"
    alias rm="rm -vI --one-file-system" # verbose, confirm large removals
fi

alias grep="grep --color=auto"
alias legacy-ssh="ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 -c 3des-cbc"
alias legacy-scp="scp -oKexAlgorithms=+diffie-hellman-group1-sha1 -c 3des-cbc"
alias emacs="emacs -nw -Q"
alias mvn17="JAVA_HOME=/usr/lib/jvm/java-17-openjdk mvn"
alias mvn11="JAVA_HOME=/usr/lib/jvm/java-11-openjdk mvn"
alias yay="yay --answerclean=n --answerdiff=n --answeredit=n"
# Random stuff I sometimes use
alias pfresh='mplayer http://live.fresh927.com.au:80/freshaac'
alias loldongs="yes loldongs | lolcat"
alias weather="curl https://wttr.in"
# End setting up aliases

# Set up useful environment variables
if [ "$TMUX" != "" ] || [ "$STY" != "" ]; then
    export TERM=screen-256color
elif [[ "$TERM" != vt* ]]; then # If something else has set our TERM to something like vt100, trust it.
    export TERM=xterm-256color
fi

unset TMPDIR
export LANG=en_US.UTF-8

# Ruby stuff, rbenv and gem PATH
if command -v rbenv >/dev/null; then
    eval "$(rbenv init -)"
fi

if [ -f /usr/share/chruby/chruby.sh ]; then
    source /usr/share/chruby/chruby.sh
    source /usr/share/chruby/auto.sh
fi

if command -v ruby >/dev/null && [ -d "$HOME/.gem/ruby" ]; then
    ruby_version="$(ruby --version | cut -d' ' -f2 | cut -d'p' -f1)"
    export PATH="$PATH:$HOME/.gem/ruby/${ruby_version}/bin"
fi

# Java path
if [ -d "/usr/lib/jvm/default" ]; then
    export JAVA_HOME="/usr/lib/jvm/default"
fi

export PATH="$PATH:$HOME/bin"
export GOPATH="$HOME/projects/go"
export DOTNET_CLI_TELEMETRY_OPTOUT="true"

export EDITOR=vim
export VISUAL=vim

export LOLCOMMITS_DEVICE="/dev/video0:width=1280:height=720"
export LOLCOMMITS_STEALTH=1
#export LOLCOMMITS_DEVICE="/dev/video0"
export LOLCOMMITS_FORK=1
# End setup of environment variables

# I don't know why my mouse speed is set in my bashrc.
# if [ "$DISPLAY" != "" ]; then
#     xset m 1/16
# fi

# SSH agent stuff
if [ ! -z "$(which ssh-agent)" ] &&  [ ! -z "$(ls ~/.ssh/identities/ 2>/dev/null)" ]; then

    if ! pgrep -u $USER ssh-agent > /dev/null; then
        ssh-agent | grep -v echo > ~/.ssh-agent-thing
    fi

    if [[ "$SSH_AGENT_PID" == "" ]]; then
        eval $(<~/.ssh-agent-thing)
    fi

    ssh-add -l >/dev/null || alias ssh='ssh-add -l >/dev/null || ssh-add ~/.ssh/identities/* && unalias ssh; ssh'
fi
# End SSH agent stuff

