# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Set up make flags
ncpus="$(nproc)"
makejobs=""

# Special case for my desktop
if [ "$ncpus" == "12" ]; then 
    makejobs="10"
else
    makejobs="$ncpus"
fi

export MAKEFLAGS="-j$makejobs"

# End setting up make flags

# Set up useful aliases
alias ls="ls --color=auto"
alias grep="grep --color=auto"

# Random stuff I sometimes use
alias pfresh='mplayer http://livestream.freshfm.com.au:8004/'
alias tgit="http_proxy=socks5://127.0.0.1:9050 git"
alias fuck='$(thefuck $(fc -ln -1))'
alias loldongs="yes loldongs | lolcat"
alias winbox='wine ~/Downloads/winbox.exe >/dev/null 2>&1 &!'

# End setting up aliases

# Set up useful environment variables
if [ "$TMUX" != "" ]; then
	export TERM=screen-256color
else
	export TERM=xterm-256color
fi


unset TMPDIR
export LANG=en_US.UTF-8
RUBY_BIN="$(find ~/.gem/ruby/ -maxdepth 1 -mindepth 1 -type d | head -n1 | tr -d '\n')"/bin
export PATH=$PATH:$RUBY_BIN
export PATH="$PATH:$HOME/bin/:/usr/lib/passenger/bin"
export GEM_HOME=~/.gem/ruby/2.0.0/ bundle
export GOPATH="$HOME/projects/go"
export JAVA_HOME="/usr/lib/jvm/default"
export EDITOR=vim
export VISUAL=vim

# End setup of environment variables

# I don't know why my mouse speed is set in my bashrc.
if [ "$DISPLAY" != "" ]; then
    xset m 1/16
fi

# SSH agent stuff
if ! pgrep -u $USER ssh-agent > /dev/null; then
    ssh-agent | grep -v echo > ~/.ssh-agent-thing
fi

if [[ "$SSH_AGENT_PID" == "" ]]; then
    eval $(<~/.ssh-agent-thing)
fi

ssh-add -l >/dev/null || alias ssh='ssh-add -l >/dev/null || ssh-add ~/.ssh/identities/* && unalias ssh; ssh'

# End SSH agent stuff
