#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Created by newuser for 5.0.2
emulate sh
source ~/.bashrc
emulate zsh

if [[ -f "$HOME/.zsh/hosts/$(hostname).zsh" ]]; then
    source "$HOME/.zsh/hosts/$(hostname).zsh"
fi

#prompt redhat
#PROMPT="[%n@%m %1~]$ "
source $HOME/.zsh/ponyhosts.zsh
export HISTFILE=$HOME/.zhistory
export SAVEHIST=999999999
export HISTSIZE=$SAVEHIST
#emulate sh
# exec pwsh -NoLogo -NoExit
bindkey -e # fix ctrl-r binding hopefully

